inoremap <buffer> <expr> = smartchr#loop(' = ', ' == ', ' === ', '=')
inoremap <buffer> <expr> # smartchr#loop('# ', '#{}<Left>')
inoremap <buffer> <expr> " smartchr#loop('""<Left>')
inoremap <buffer> <expr> > smartchr#loop(' > ', ' => ', ' <=> ', ' >> ')
inoremap <buffer> <expr> / smartchr#loop(' / ', '//<Left>')
inoremap <buffer> <expr> <bar> smartchr#loop('<bar>', '<bar><bar>', '<bar><bar><Left>')
